#ifndef __ISCSI_DEFINE_H__
#define __ISCSI_DEFINE_H__

// variables

#define MAX_SUPPORTED_CONNS 4

#define ISCSI_BUFFER_SIZE 8192
#define ISCSI_CONNECTION_PARAMETER_BUFFER_SIZE 8192

#define ISCSI_MAX_CMD_SN 0xFFFFFFFF

#define ISCSI_TARGET_TIMEOUT_MS 100
#define ISCSI_TARGET_MEMORY_SIZE 8192
#define ISCSI_TARGET_SENSE_BUFFER_SIZE 32

#define SCSI_CDB_LENGTH 16

#define ISCSI_TRANSFER_ENTRY_SIZE 8192


// connection parameter default values
#define ISCSI_CONNECTION_PARAMETER_MAX_CONNECTIONS           1
#define ISCSI_CONNECTION_PARAMETER_INITIAL_R2T               1
#define ISCSI_CONNECTION_PARAMETER_IMMEDIATE_DATA            1
#define ISCSI_CONNECTION_PARAMETER_MAX_BURST_LENGTH          8192
#define ISCSI_CONNECTION_PARAMETER_FIRST_BURST_LENGTH        8192
#define ISCSI_CONNECTION_PARAMETER_DATA_PDU_IN_ORDER         1
#define ISCSI_CONNECTION_PARAMETER_DATA_SEQUENCE_IN_ORDER    1
#define ISCSI_CONNECTION_PARAMETER_DEFAULT_TIME_2_WAIT       10
#define ISCSI_CONNECTION_PARAMETER_DEFAULT_TIME_2_RETAIN     10
#define ISCSI_CONNECTION_PARAMETER_MAX_OUTSTANDING_R2T       10

#endif // __ISCSI_DEFINE_H__
