# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/100/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/100/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phirasit/project/san-adapter/iscsi-cli

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phirasit/project/san-adapter/iscsi-cli

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/100/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/100/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phirasit/project/san-adapter/iscsi-cli/CMakeFiles /home/phirasit/project/san-adapter/iscsi-cli/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phirasit/project/san-adapter/iscsi-cli/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iscsi

# Build rule for target.
iscsi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iscsi
.PHONY : iscsi

# fast build rule for target.
iscsi/fast:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/build
.PHONY : iscsi/fast

iscsi_buffer.o: iscsi_buffer.c.o

.PHONY : iscsi_buffer.o

# target to build an object file
iscsi_buffer.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_buffer.c.o
.PHONY : iscsi_buffer.c.o

iscsi_buffer.i: iscsi_buffer.c.i

.PHONY : iscsi_buffer.i

# target to preprocess a source file
iscsi_buffer.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_buffer.c.i
.PHONY : iscsi_buffer.c.i

iscsi_buffer.s: iscsi_buffer.c.s

.PHONY : iscsi_buffer.s

# target to generate assembly for a file
iscsi_buffer.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_buffer.c.s
.PHONY : iscsi_buffer.c.s

iscsi_connection.o: iscsi_connection.c.o

.PHONY : iscsi_connection.o

# target to build an object file
iscsi_connection.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_connection.c.o
.PHONY : iscsi_connection.c.o

iscsi_connection.i: iscsi_connection.c.i

.PHONY : iscsi_connection.i

# target to preprocess a source file
iscsi_connection.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_connection.c.i
.PHONY : iscsi_connection.c.i

iscsi_connection.s: iscsi_connection.c.s

.PHONY : iscsi_connection.s

# target to generate assembly for a file
iscsi_connection.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_connection.c.s
.PHONY : iscsi_connection.c.s

iscsi_connection_parameter.o: iscsi_connection_parameter.c.o

.PHONY : iscsi_connection_parameter.o

# target to build an object file
iscsi_connection_parameter.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_connection_parameter.c.o
.PHONY : iscsi_connection_parameter.c.o

iscsi_connection_parameter.i: iscsi_connection_parameter.c.i

.PHONY : iscsi_connection_parameter.i

# target to preprocess a source file
iscsi_connection_parameter.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_connection_parameter.c.i
.PHONY : iscsi_connection_parameter.c.i

iscsi_connection_parameter.s: iscsi_connection_parameter.c.s

.PHONY : iscsi_connection_parameter.s

# target to generate assembly for a file
iscsi_connection_parameter.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_connection_parameter.c.s
.PHONY : iscsi_connection_parameter.c.s

iscsi_logger.o: iscsi_logger.c.o

.PHONY : iscsi_logger.o

# target to build an object file
iscsi_logger.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_logger.c.o
.PHONY : iscsi_logger.c.o

iscsi_logger.i: iscsi_logger.c.i

.PHONY : iscsi_logger.i

# target to preprocess a source file
iscsi_logger.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_logger.c.i
.PHONY : iscsi_logger.c.i

iscsi_logger.s: iscsi_logger.c.s

.PHONY : iscsi_logger.s

# target to generate assembly for a file
iscsi_logger.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_logger.c.s
.PHONY : iscsi_logger.c.s

iscsi_pdu.o: iscsi_pdu.c.o

.PHONY : iscsi_pdu.o

# target to build an object file
iscsi_pdu.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_pdu.c.o
.PHONY : iscsi_pdu.c.o

iscsi_pdu.i: iscsi_pdu.c.i

.PHONY : iscsi_pdu.i

# target to preprocess a source file
iscsi_pdu.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_pdu.c.i
.PHONY : iscsi_pdu.c.i

iscsi_pdu.s: iscsi_pdu.c.s

.PHONY : iscsi_pdu.s

# target to generate assembly for a file
iscsi_pdu.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_pdu.c.s
.PHONY : iscsi_pdu.c.s

iscsi_server.o: iscsi_server.c.o

.PHONY : iscsi_server.o

# target to build an object file
iscsi_server.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_server.c.o
.PHONY : iscsi_server.c.o

iscsi_server.i: iscsi_server.c.i

.PHONY : iscsi_server.i

# target to preprocess a source file
iscsi_server.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_server.c.i
.PHONY : iscsi_server.c.i

iscsi_server.s: iscsi_server.c.s

.PHONY : iscsi_server.s

# target to generate assembly for a file
iscsi_server.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_server.c.s
.PHONY : iscsi_server.c.s

iscsi_session.o: iscsi_session.c.o

.PHONY : iscsi_session.o

# target to build an object file
iscsi_session.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_session.c.o
.PHONY : iscsi_session.c.o

iscsi_session.i: iscsi_session.c.i

.PHONY : iscsi_session.i

# target to preprocess a source file
iscsi_session.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_session.c.i
.PHONY : iscsi_session.c.i

iscsi_session.s: iscsi_session.c.s

.PHONY : iscsi_session.s

# target to generate assembly for a file
iscsi_session.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_session.c.s
.PHONY : iscsi_session.c.s

iscsi_target.o: iscsi_target.c.o

.PHONY : iscsi_target.o

# target to build an object file
iscsi_target.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_target.c.o
.PHONY : iscsi_target.c.o

iscsi_target.i: iscsi_target.c.i

.PHONY : iscsi_target.i

# target to preprocess a source file
iscsi_target.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_target.c.i
.PHONY : iscsi_target.c.i

iscsi_target.s: iscsi_target.c.s

.PHONY : iscsi_target.s

# target to generate assembly for a file
iscsi_target.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_target.c.s
.PHONY : iscsi_target.c.s

iscsi_transfer_entry.o: iscsi_transfer_entry.c.o

.PHONY : iscsi_transfer_entry.o

# target to build an object file
iscsi_transfer_entry.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_transfer_entry.c.o
.PHONY : iscsi_transfer_entry.c.o

iscsi_transfer_entry.i: iscsi_transfer_entry.c.i

.PHONY : iscsi_transfer_entry.i

# target to preprocess a source file
iscsi_transfer_entry.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_transfer_entry.c.i
.PHONY : iscsi_transfer_entry.c.i

iscsi_transfer_entry.s: iscsi_transfer_entry.c.s

.PHONY : iscsi_transfer_entry.s

# target to generate assembly for a file
iscsi_transfer_entry.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_transfer_entry.c.s
.PHONY : iscsi_transfer_entry.c.s

iscsi_utility.o: iscsi_utility.c.o

.PHONY : iscsi_utility.o

# target to build an object file
iscsi_utility.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_utility.c.o
.PHONY : iscsi_utility.c.o

iscsi_utility.i: iscsi_utility.c.i

.PHONY : iscsi_utility.i

# target to preprocess a source file
iscsi_utility.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_utility.c.i
.PHONY : iscsi_utility.c.i

iscsi_utility.s: iscsi_utility.c.s

.PHONY : iscsi_utility.s

# target to generate assembly for a file
iscsi_utility.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/iscsi_utility.c.s
.PHONY : iscsi_utility.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/main.c.s
.PHONY : main.c.s

request/cmd.o: request/cmd.c.o

.PHONY : request/cmd.o

# target to build an object file
request/cmd.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/cmd.c.o
.PHONY : request/cmd.c.o

request/cmd.i: request/cmd.c.i

.PHONY : request/cmd.i

# target to preprocess a source file
request/cmd.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/cmd.c.i
.PHONY : request/cmd.c.i

request/cmd.s: request/cmd.c.s

.PHONY : request/cmd.s

# target to generate assembly for a file
request/cmd.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/cmd.c.s
.PHONY : request/cmd.c.s

request/data_in.o: request/data_in.c.o

.PHONY : request/data_in.o

# target to build an object file
request/data_in.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/data_in.c.o
.PHONY : request/data_in.c.o

request/data_in.i: request/data_in.c.i

.PHONY : request/data_in.i

# target to preprocess a source file
request/data_in.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/data_in.c.i
.PHONY : request/data_in.c.i

request/data_in.s: request/data_in.c.s

.PHONY : request/data_in.s

# target to generate assembly for a file
request/data_in.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/data_in.c.s
.PHONY : request/data_in.c.s

request/data_out.o: request/data_out.c.o

.PHONY : request/data_out.o

# target to build an object file
request/data_out.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/data_out.c.o
.PHONY : request/data_out.c.o

request/data_out.i: request/data_out.c.i

.PHONY : request/data_out.i

# target to preprocess a source file
request/data_out.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/data_out.c.i
.PHONY : request/data_out.c.i

request/data_out.s: request/data_out.c.s

.PHONY : request/data_out.s

# target to generate assembly for a file
request/data_out.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/data_out.c.s
.PHONY : request/data_out.c.s

request/login.o: request/login.c.o

.PHONY : request/login.o

# target to build an object file
request/login.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/login.c.o
.PHONY : request/login.c.o

request/login.i: request/login.c.i

.PHONY : request/login.i

# target to preprocess a source file
request/login.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/login.c.i
.PHONY : request/login.c.i

request/login.s: request/login.c.s

.PHONY : request/login.s

# target to generate assembly for a file
request/login.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/login.c.s
.PHONY : request/login.c.s

request/logout.o: request/logout.c.o

.PHONY : request/logout.o

# target to build an object file
request/logout.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/logout.c.o
.PHONY : request/logout.c.o

request/logout.i: request/logout.c.i

.PHONY : request/logout.i

# target to preprocess a source file
request/logout.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/logout.c.i
.PHONY : request/logout.c.i

request/logout.s: request/logout.c.s

.PHONY : request/logout.s

# target to generate assembly for a file
request/logout.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/logout.c.s
.PHONY : request/logout.c.s

request/nop.o: request/nop.c.o

.PHONY : request/nop.o

# target to build an object file
request/nop.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/nop.c.o
.PHONY : request/nop.c.o

request/nop.i: request/nop.c.i

.PHONY : request/nop.i

# target to preprocess a source file
request/nop.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/nop.c.i
.PHONY : request/nop.c.i

request/nop.s: request/nop.c.s

.PHONY : request/nop.s

# target to generate assembly for a file
request/nop.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/nop.c.s
.PHONY : request/nop.c.s

request/r2t.o: request/r2t.c.o

.PHONY : request/r2t.o

# target to build an object file
request/r2t.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/r2t.c.o
.PHONY : request/r2t.c.o

request/r2t.i: request/r2t.c.i

.PHONY : request/r2t.i

# target to preprocess a source file
request/r2t.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/r2t.c.i
.PHONY : request/r2t.c.i

request/r2t.s: request/r2t.c.s

.PHONY : request/r2t.s

# target to generate assembly for a file
request/r2t.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/r2t.c.s
.PHONY : request/r2t.c.s

request/reject.o: request/reject.c.o

.PHONY : request/reject.o

# target to build an object file
request/reject.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/reject.c.o
.PHONY : request/reject.c.o

request/reject.i: request/reject.c.i

.PHONY : request/reject.i

# target to preprocess a source file
request/reject.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/reject.c.i
.PHONY : request/reject.c.i

request/reject.s: request/reject.c.s

.PHONY : request/reject.s

# target to generate assembly for a file
request/reject.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/reject.c.s
.PHONY : request/reject.c.s

request/text.o: request/text.c.o

.PHONY : request/text.o

# target to build an object file
request/text.c.o:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/text.c.o
.PHONY : request/text.c.o

request/text.i: request/text.c.i

.PHONY : request/text.i

# target to preprocess a source file
request/text.c.i:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/text.c.i
.PHONY : request/text.c.i

request/text.s: request/text.c.s

.PHONY : request/text.s

# target to generate assembly for a file
request/text.c.s:
	$(MAKE) -f CMakeFiles/iscsi.dir/build.make CMakeFiles/iscsi.dir/request/text.c.s
.PHONY : request/text.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... iscsi"
	@echo "... edit_cache"
	@echo "... iscsi_buffer.o"
	@echo "... iscsi_buffer.i"
	@echo "... iscsi_buffer.s"
	@echo "... iscsi_connection.o"
	@echo "... iscsi_connection.i"
	@echo "... iscsi_connection.s"
	@echo "... iscsi_connection_parameter.o"
	@echo "... iscsi_connection_parameter.i"
	@echo "... iscsi_connection_parameter.s"
	@echo "... iscsi_logger.o"
	@echo "... iscsi_logger.i"
	@echo "... iscsi_logger.s"
	@echo "... iscsi_pdu.o"
	@echo "... iscsi_pdu.i"
	@echo "... iscsi_pdu.s"
	@echo "... iscsi_server.o"
	@echo "... iscsi_server.i"
	@echo "... iscsi_server.s"
	@echo "... iscsi_session.o"
	@echo "... iscsi_session.i"
	@echo "... iscsi_session.s"
	@echo "... iscsi_target.o"
	@echo "... iscsi_target.i"
	@echo "... iscsi_target.s"
	@echo "... iscsi_transfer_entry.o"
	@echo "... iscsi_transfer_entry.i"
	@echo "... iscsi_transfer_entry.s"
	@echo "... iscsi_utility.o"
	@echo "... iscsi_utility.i"
	@echo "... iscsi_utility.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... request/cmd.o"
	@echo "... request/cmd.i"
	@echo "... request/cmd.s"
	@echo "... request/data_in.o"
	@echo "... request/data_in.i"
	@echo "... request/data_in.s"
	@echo "... request/data_out.o"
	@echo "... request/data_out.i"
	@echo "... request/data_out.s"
	@echo "... request/login.o"
	@echo "... request/login.i"
	@echo "... request/login.s"
	@echo "... request/logout.o"
	@echo "... request/logout.i"
	@echo "... request/logout.s"
	@echo "... request/nop.o"
	@echo "... request/nop.i"
	@echo "... request/nop.s"
	@echo "... request/r2t.o"
	@echo "... request/r2t.i"
	@echo "... request/r2t.s"
	@echo "... request/reject.o"
	@echo "... request/reject.i"
	@echo "... request/reject.s"
	@echo "... request/text.o"
	@echo "... request/text.i"
	@echo "... request/text.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

